<?php
function addSmilies($text) {
        //codes and its relevant smiley image path
        $codesToConvert = array(    
                '[b]'    =>  '<b>',
				'[/b]'    =>  '</b>',
				':luv)'    =>  '<br><img src="smilies/love.png" alt="love" /><br>',
				':tst)'    =>  '<br><img src="smilies/toast.png" alt="toast" /><br>',
				':sun)'    =>  '<br><img src="smilies/sunny.png" alt="sunny" /><br>',
				':crw)'    =>  '<br><img src="smilies/crown.png" alt="crown" /><br>',
				':hbd)'    =>  '<br><img src="smilies/birthday.png" alt="happy birthday" /><br>',
				':nig)'    =>  '<br><img src="smilies/nigeria.gif" alt="nigerian flag" /><br>',
				':)'    =>  '<img src="smilies/smile.png" alt="smile" align=absmiddle />', 
				':-)'   =>  '<img src="smilies/smile.png" alt="smile" align=absmiddle />', 
                ':D'    =>  '<img src="smilies/laugh.png" alt="laugh" align=absmiddle />',
                ':d'    =>  '<img src="smilies/laugh.png" alt="laugh" align=absmiddle />',
                ';)'    =>  '<img src="smilies/wink.png" alt="wink" align=absmiddle />',
                ':P'    =>  '<img src="smilies/tounge.png" alt="tounge" align=absmiddle />',
                ':-P'   =>  '<img src="smilies/tounge.png" alt="tounge" align=absmiddle />',
                ':-p'   =>  '<img src="smilies/tounge.png" alt="tounge" align=absmiddle />',
                ':p'    =>  '<img src="smilies/tounge.png" alt="tounge" align=absmiddle />',
                ':('    =>  '<img src="smilies/sad.png" alt="sad face" align=absmiddle />',
                ':o'    =>  '<img src="smilies/shock.png" alt="shock" align=absmiddle />',
                ':O'    =>  '<img src="smilies/shock.png" alt="shock" align=absmiddle />',
                ':0'    =>  '<img src="smilies/shock.png" alt="shock" align=absmiddle />',
                ':|'    =>  '<img src="smilies/straight.png" alt="straight face" align=absmiddle />',
				'&lt;'    =>  '<br><br><',
				'&gt;'    =>  '><br>',
				"\'"     =>  "'",
				"\\'"     =>  "'",
				"\\\'"     =>  "'",
                ':-|'   =>  '<img src="smilies/straight.png" alt="straight face" align=absmiddle />',
				 '�'    =>  '-',			
				'�'    =>  "'",
				'&ldquo;'    =>  '"',
				'&lsquo'    =>  '"',
				'�'    =>  '"',
				'&lsquo;'    =>  '"',
				'&prime;'   =>  '"',
				'&hellip'   =>  ' and ',
				'&hellip;'   =>  ' and ',
				'&ndash'    =>  '-',
				'&mdash'    =>  '-',
				'&frasl'    =>  '-',
				'&#039'    =>  "'",
				';'    =>  '',
				'&acirc;��'    =>  '-',
				'&acirc;'    =>  '-',
				'&#039;'	=>  "'",
				'&acirc;��'    =>  "'",
				'�'    =>  "'",
				'�'    =>  "'",
				'&nbsp;'    =>  " ",
				'&#39;'    =>  "'",
				'&rdquo;'  =>  '"',
				 '&rsquo;'  =>  "'",
				 '&nbsp;'  =>  ' ',
				'&quot'    =>  ''
               );
        //Replaces smilies codes / add smilies images: IMG html tags and return rendered text
        return (strtr($text, $codesToConvert));
        
    }//END addSmilies()
?>